name: CI/CD - Build and Publish NuGet Package

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up .NET SDK (ensure that you're using the correct version)
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # Step 3: Restore the NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore

      # Passo 4: Publicar o projeto, especificando o diretório de saída
      - name: Publish the project
        run: |
          dotnet publish --configuration Release --output ./publish_output
      
      # Passo 5: Empacotar o NuGet, se necessário
      - name: Pack the project
        run: |
          dotnet pack --configuration Release --output ./nuget_output
      
      # Passo 6: Publicar o pacote no NuGet (substitua pelos detalhes da sua conta)
      - name: Publish NuGet package
        run: |
          dotnet nuget push ./nuget_output/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json